### ISSUE TITLE
Scroll-spy Overlap

### ISSUE THREAD

**Issue by rdvelazquez** [veg/hyphy-vision#117]
There seems to be an issue with the bootstrap that causes the scroll-spy to overlap with the main content when the browser window is a certain size. 

![bootstrap capture 2](https://user-images.githubusercontent.com/25244432/36382499-1a412e2a-1557-11e8-852e-b590ffa06b02.gif)

**Comment by stevenweaver** [comment]
A quick fix would be to increase the width at which the CSS media query changes the sidebar nav to hidden.

**Comment by rdvelazquez** [comment]
Closed by #110
