### ISSUE TITLE
RELAX hyphy vision not letting me upload .json files

### ISSUE THREAD

**Issue by ltornabene** [veg/hyphy-vision#12]
I can select the file to upload, but it won't actually upload the file to view the results. I tried using several .json files on Safari and Firefox on two different computers.

**Comment by stevenweaver** [comment]
Hello, 

A new version of HyPhy-vision was released Friday afternoon that introduced this issue. 
I've resolved the issue this morning. Please feel free to try again. 

Thank you,
Steven

**Comment by anne-maria** [comment]
Hi, I have also encountered a problem with hyphy vision. 
When I upload Relax json files the correct table and figures are displayed but the test summary (in the blue box) is wrong (shows the default values).
I still had the consoles open so I got the correct values from there... but at first I was quite confused and I think it might confuse others, too.

AM

**Comment by stevenweaver** [comment]
Hello @anne-maria,

Apologies for the oversight. The issue should not be resolved.

Best,
Steven

**Comment by anne-maria** [comment]
Hi Steven,
works perfectly now! Thanks for the fast fix! 
Cheers,
Anne-Maria
