### ISSUE TITLE
Migrate to Bootstrap v4

### ISSUE THREAD

**Issue by stevenweaver** [veg/hyphy-vision#128]
__General Outline of Tasks__

 - [x] Convert the .less file to a .scss file and change the dependency to v4 (SW) (#127)
 - [x] Combine the .css and .scss into one .scss file (#130)
 - [x] Combine redundant ID’s/classes/tags (i.e if there are multiple `.btn` definitions in the .scss file... combine these into one definition and sort out any redundancy or contradictions. Hopefully there aren't too many of these)
 - [x] Remove any `! important`s (these negate the ability of inline styling to override css styles) (SW already removed the `!important`s from the .scss file so we will just need to check the .css file)
 - [x] Fix navbars
 - [x] Fix view json modal
 - [x] Fix scrollspy highlighting
 - [x] Test to see if anything else needs to be addressed

**Comment by rdvelazquez** [comment]
Closed by #141
