### ISSUE TITLE
Legend export in RELAX

### ISSUE THREAD

**Issue by uhaifabioinfo** [veg/hyphy-vision#13]
Hi,

could you please add the legend in the png figure export, please?

Thanks!
David.

**Comment by stevenweaver** [comment]
Fix has not been implemented in test.datamonkey.org quite yet, but has been resolved on our github pages. 

Reopening until version 0.2.0 is being used by test.datamonkey.org.

**Comment by stevenweaver** [comment]
Datamonkey 0.4.2 has been released.
