### ISSUE TITLE
aBSREL tooltip

### ISSUE THREAD

**Issue by stephenshank** [veg/hyphy-vision#133]
The aBSREL tree tooltip does not appear at the location of the mouse hover (see image below). It is even possible to place it entirely off screen.

Ideally, it should be placed in the Tree component so that other methods can utilize tooltips.

![image](https://user-images.githubusercontent.com/8673708/38566495-cb24c612-3cb1-11e8-8d37-e94a42a6533d.png)

**Comment by rdvelazquez** [comment]
Addressed by #158.
