### ISSUE TITLE
[BUSTED] Reduce amount of site ticks on evidence ratio plot

### ISSUE THREAD

**Issue by stevenweaver** [veg/hyphy-vision#172]
<img width="964" alt="screen shot 2018-09-26 at 5 05 23 pm" src="https://user-images.githubusercontent.com/535261/46109406-79fe9d80-c1ae-11e8-9405-8290762867ea.png">

**Comment by rdvelazquez** [comment]
Related to veg/datamonkey-js#169

Closed by: https://github.com/veg/hyphy-vision/commit/ed93db1b47340f79addfe0409c4dab3edf082d09
