### ISSUE TITLE
p-values in MEME output problem

### ISSUE THREAD

**Issue by vguerracanedo** [veg/hyphy-vision#181]
Dear HYPHY team, 

I'm having a hard time interpreting the p-value results within the plot. I have 2 foreground branches selected out of 6. Why can't I see the p-value of site 263 well represented in the graph? 

P-values organized by significance
<img width="754" alt="screen shot 2018-12-26 at 5 17 52 pm" src="https://user-images.githubusercontent.com/11927310/50458591-33961780-0932-11e9-9297-9c9bf49579c5.png">

Plot of p-values
![datamonkey-chart](https://user-images.githubusercontent.com/11927310/50458554-ea45c800-0931-11e9-90f3-234262e22ef2.png)

**Comment by rdvelazquez** [comment]
@vguerracanedo could you share the link to this result. I'll look into it. Thanks!
