### ISSUE TITLE
[aBSREL/BUSTED] Layout issues.

### ISSUE THREAD

**Issue by spond** [veg/hyphy-vision#19]
When &omega; charts are displayed, there is some ugliness with overlap if your window is not sized just right. See attached.

<img width="1407" alt="screen shot 2016-08-18 at 10 08 10 am" src="https://cloud.githubusercontent.com/assets/1018513/17758600/b75ec402-652b-11e6-8788-1592e8f0ec2e.png">

**Comment by stevenweaver** [comment]
This issue was resolved in 0.2.1. The next datamonkey push on Thursday, 2016-08-25 will include this fix.
