### ISSUE TITLE
[BUSTED] BUSTEDS changes

### ISSUE THREAD

**Issue by srwis** [veg/hyphy-vision#196]
Hi,

For the inclusion of BUSTED[S] I think the vision page could use a display for the synonymous rate category as well as the omegas. Or at the very least add a column for the CV of SRV to the model fits section.

Additionally, I think since BUSTED[S] will be the default when the new version of HyPhy is released we should add a line to this:

> BUSTED found evidence (LRT, p-value = 0.001 < .05) of gene-wide episodic diversifying selection in the selected test branches of your phylogeny. Therefore, there is evidence that at least one site on at least one test branch has experienced diversifying selection.

to say something like:

> BUSTED **with/out synonymous rate variation** found evidence (LRT, p-value = 0.001 < .05) of gene-wide episodic diversifying selection in the selected test branches of your phylogeny. Therefore, there is evidence that at least one site on at least one test branch has experienced diversifying selection.

Let me know if you need any info from me,
Sadie

**Comment by stephenshank** [comment]
Without SRV:
![image](https://user-images.githubusercontent.com/8673708/70081162-050acd00-15d6-11ea-8091-6e764072063b.png)

And with:
![image](https://user-images.githubusercontent.com/8673708/70081274-3388a800-15d6-11ea-8934-d6374827a3a9.png)
