### ISSUE TITLE
Productize SLAC widget

### ISSUE THREAD

**Issue by jzehr** [veg/hyphy-vision#202]

**Comment by stevenweaver** [comment]
I've completed some of this issue while implementing #207. Please contact me if work on this issue hasn't started yet.

**Comment by stephenshank** [comment]
This file contains an interesting edge case where the root was automatically renamed to `Node52_1`, resulting in a discrepancy of nodes that are in the tree's `node_order` and the sequence data that is produced.

A simple matching before sorting may be all that's required.

[yokoyama.zip](https://github.com/veg/hyphy-vision/files/4295259/yokoyama.zip)
