### ISSUE TITLE
Uncaught SyntaxError: Unexpected token i in JSON at position 35491947

### ISSUE THREAD

**Issue by migrau** [veg/hyphy-vision#303]
After run SLAC with HYPHY 2.5.8(MP) for Linux on x86_64 (`hyphy slac --alignment in.fas --tree in.treefile`), I try uploading the JSON (http://vision.hyphy.org/slac) but nothing happens. 
If I check the web browser Console messages there is an error:
`Uncaught SyntaxError: Unexpected token i in JSON at position 35491947`

It's a version's problem? Many thanks,

**Comment by stevenweaver** [comment]
Duplicate of #1140
