### ISSUE TITLE
[BUSTED] New JSON compatibility

### ISSUE THREAD

**Issue by spond** [veg/hyphy-vision#51]
Please update the result processor to read data from the new JSON format (example included). There are numerous changes to how the data are stored, although the actual data are the same.

1. Key values
2. Branch lengths stored as attributes
3. Different analysis summary 
4. BUSTED now supports multiple partitions, so it is necessary to update the tree viewer to deal with this (attached example includes partitions)

[partitioned.nex.BUSTED.json.zip](https://github.com/veg/hyphy-vision/files/1222161/partitioned.nex.BUSTED.json.zip)

**Comment by stephenshank** [comment]
Please see

http://sshank.datamonkey.org/pages/busted/

and let me know your thoughts. In particular, the partition functionality works as follows:

![busted-partitions](https://user-images.githubusercontent.com/8673708/29380502-ebf61c8e-8293-11e7-9651-976f3a3cbee2.gif)

**Comment by sjspielman** [comment]
Awesome! A few things - 
1) What's up with the tree for partition 3? It is a bad tree or a rendering problem?
2) File load and downloading of input data still not working (which you probably know..)
3) This may or may not be a general problem: when downloading a CSV from the table, this is the output's header: 
`Site index,Unconstrained likelihood,Constrained likelihood,undefined,Optimized Null Likelihood,Constrained Statistic,Optimized Null Statistic`. 
Note the column named "undefined".

**Comment by stephenshank** [comment]
1. Looks like bad tree... the branch lengths in the string are all -1: `(AF_231119:-1,((AF082576:-1,AF231113:-1)Node3:-1,((AF231115:-1,AF231114:-1)Node7:-1,(((AF186242:-1,AF186243:-1)Node12:-1,((AF186241:-1,AF187824:-1)Node16:-1,AF231116:-1)Node15:-1)Node11:-1,(AF231118:-1,AF234767:-1)Node20:-1)Node10:-1)Node6:-1)Node2:-1,AF231117:-1)`
2. Working on file loading now.
3. Great catch! Fortunately it was just a rogue comma, which has been deleted.

**Comment by sjspielman** [comment]
I've noticed trees with -1 branch lengths in a BUSTED json of mine as well. Let me go track down that bug.

**Comment by sjspielman** [comment]
That bug does not exist in v2.31-dev from what I can see. We should be ok.

**Comment by spond** [comment]
Dear @stephenshank,

That looks very nice! Thank you for implementing the change. Regarding the branch lengths: you need to collect them from a different dict, namely: `branch attributes`, and not rely on the lengths in the tree.  I'll modify the behavior of the analyses NOT to output -1 (which means `missing`) in the tree strings, but rather the "default" set of branch lengths (whatever the user supplied). But from now, let's assume that the trees will only be supplying topologies, and the branch lengths and attributes will be supplied via annotated dicts. 

Best,
Sergei
