### ISSUE TITLE
json files not loading

### ISSUE THREAD

**Issue by loloyohe** [veg/hyphy-vision#60]
It does not appear the .json file will not load after clicking "Load" in top right corner and selecting the file. Nothing on the page changes. Please let me know if you need any more information.

**Comment by stephenshank** [comment]
Hello @loloyohe ,

A few questions...
1) Which method are you using?
2) Where did you get the JSON file from (for example: uploading data to test.datamonkey.org, or running HyPhy via the command line)?

Also, I assume you are trying to load on vision.hyphy.org (i.e., you are not running hyphy-vision locally).

If possible, it would be helpful to have a copy of the JSON file (either uploaded here or sent via email).

**Comment by loloyohe** [comment]
Hi @stephenshank,
1. I am using RELAX
2. I ran HyPhy locally on my computer to generate the .json file

Yes, I am using the http://vision.hyphy.org/pages/relax/# to upload my .json file.  Will send via e-mail. Thanks for getting back to me!

**Comment by Astahlke** [comment]
I'm having the same issue in both Chrome and Safari with this file. I ran HyPhy via command line. I changed the extension from .json to .txt here for uploading purposes. 

Thanks!
[ENSSHAG00000000241.ABSREL.txt](https://github.com/veg/hyphy-vision/files/1289328/ENSSHAG00000000241.ABSREL.txt)

**Comment by spond** [comment]
Dear @loloyohe and @Astahlke,

My apologies for this. We have substantially improved the implementation of all core selection analyses, and this entailed the change in how JSON files are structured. The vision.hyphy.org pages expect JSON files produced by HyPhy version 2.3.3 or later. 

Please consider downloading the current version of HyPhy (2.3.3 or later), running the analyses in it and then loading the JSON files into vision.hyphy.org

Please let me know if this approach works.

Best,
Sergei

**Comment by mht85** [comment]
Hi Sergei,

Re-ran hyphy with version 2.3.320170924 but the JSON file still doesn't load.

[test.fas.ABSREL.json.txt](https://github.com/veg/hyphy-vision/files/1335330/test.fas.ABSREL.json.txt)

**Comment by stephenshank** [comment]
Dear @loloyohe, @Astahlke and @mht85,

Apologies for any inconvenience, as we are in the midst of major changes to HyPhy, Datamonkey, and HyPhy-Vision. The current [HyPhy Vision](http://vision.hyphy.org) should be able to load output from HyPhy 2.3.4 and above. Please let me know if you run into any issues.

Best,
Stephen

**Comment by ralanharris** [comment]
I generated aBSREL json files using HyPhy version 2.3.11 and I am having the same issue with the json file not loading and nothing at all changing on the page when I use this page:

http://vision.hyphy.org/methods/absrel/

I have tried this in Chrome and Firefox and both have the same issue.

**Comment by ralanharris** [comment]
The json file was generated using a local hyphy build from github.  The version when I run hyphy is this:

HYPHY 2.3.1120180322beta(MP) for Linux on x86_64

**Comment by luigibertolotti** [comment]
Hei!
may be a silly suggestion, but check your input file: sample names do not have to include "-" or "/"... just "_" is allowed...
Best

Luigi
