### ISSUE TITLE
Hyphy Vision MEME web version error

### ISSUE THREAD

**Issue by engwbc** [veg/hyphy-vision#612]
Hi,

I am currently trying to upload and visualise my MEME.json file to the web version of Hyphy Vision but I am getting this page view:
![image](https://user-images.githubusercontent.com/90303656/132452009-566889cb-9063-461a-aae9-2eb59060a740.png)

Some of these tools seem to load fine (i.e. FEL, FUBAR) while MEME and SLAC, for instance, are having issues. 

Thanks.

**Comment by spond** [comment]
Dear @engwbc,

This bug was introduced during a recent code update: @stephenshank and/or @stevenweaver : can you please check?

<img width="1526" alt="image" src="https://user-images.githubusercontent.com/1018513/132518957-12f0d5e6-4b0e-4a57-9c60-cb01492fe2dc.png">

Best,
Sergei

**Comment by stevenweaver** [comment]
Dear @engwbc, 

Thank you for this bug report. I released a new version of hyphy-vision yesterday, and forgot about the issue at release despite noticing during development. 

The issue has been resolved. 

Best,
Steven
