### ISSUE TITLE
BUSTED suggestions

### ISSUE THREAD

**Issue by spond** [veg/hyphy-vision#62]
Dear @stephenshank,

Please consider making the following changes / improvements to the BUSTED app

- [x] We may want to increase the number of significant digits for some fields reported in the `Model Fits` table. Specifically, the weight of &omega; (e.g 0% for &omega;3 in the example analysis). We should try to show at least one significant digit that's not 0.
- [x] &omega; distribution charts clip the x-axis tick marks at the right edge of the plot
- [ ] &omega; distribution charts PNG export does not work in Safari (nothing happens).
- [x] The site table does not interact well with the range selector, when the table is not at the 1st row (see attached GIF)
- [x] The range selector is a bit counterintuitive: the boxes impose conjunctive constraints (which is fine, but not clear from the UI), and it is also not clear what you are supposed to type in the boxes.
- [x] (this is common to other analyses as well) The name of the input file is styled like a link, but clicking on it does not result in an action.
- [x] (this is common to other analyses as well) Clicking on the HyPhy vision logo (top left) results in no action.
- [ ] (this is common to other analyses as well) The tree viewer in the radial mode shrinks the tree way too much.

Best,
Sergei

![sep-07-2017 13-45-35](https://user-images.githubusercontent.com/1018513/30177237-30313424-93d3-11e7-8b2c-41d8e5a0ee26.gif)

**Comment by stevenweaver** [comment]
Closing and creating different issue for remaining checkmark
