### ISSUE TITLE
Issue with Hyphy Vision on galaxy and datamonkey.

### ISSUE THREAD

**Issue by RoberthAnthonyRojasChavez** [veg/hyphy-vision#712]
Hi, I have been running into an issue, I would appreciate some help with this.

I cannot load the output json file from HYPHY-SLAC into either Hyphy-Vision from usegalaxy.org, usegalaxy.eu or Datamonkey. I am running SLAC on Galaxy (Galaxy Version 2.5.31+galaxy1). I am trying to run HYPHY on 150 Nucleotides alignment of 14820 sequences. The resulting json file is only about 21MB, I often run into troubles dealing with larger data files (~65MB) but this is too small to be a size issue. I have SLAC ran on different portions of the dataset (different 150 Nucleotide positions from the same 14820 sequences), I have multiple json files that are about 21-22MB in size that used the same Phylogeny input, just different sections of the alignment, these json files do work nicely with either Galaxy visualizer or datamonkey's hyphy-vision. 
I have a few other portions of my sequences that also return json files that cannot be opened but it is likely all the same issue. 
I will be more than happy to provide the faulty files, and files that did work so that we can troubleshoot the issue.

**Comment by stevenweaver** [comment]
Dear @RoberthAnthonyRojasChavez, 

Thank you for reporting this issue. Yes, please provide the faulty files either here, or send them to sweaver@temple.edu if you would like for them to be sent more discretely. I'll be happy to take a look once I have them.

Best,
Steven

**Comment by RoberthAnthonyRojasChavez** [comment]
Thank you so much for your time Steven,

I am attaching an example of one of the faulty json files and one of the good json files I produced with the same tree but different sections of the sequence alignment. 

Kind regards,
Anthony
[Good_json_file_2.txt](https://github.com/veg/hyphy-vision/files/7944086/Good_json_file_2.txt)
[Faulty_json_file_1.txt](https://github.com/veg/hyphy-vision/files/7944088/Faulty_json_file_1.txt)

**Comment by RoberthAnthonyRojasChavez** [comment]
> Dear @RoberthAnthonyRojasChavez,
> 
> Thank you for reporting this issue. Yes, please provide the faulty files either here, or send them to [sweaver@temple.edu](mailto:sweaver@temple.edu) if you would like for them to be sent more discreetly. I'll be happy to take a look once I have them.
> 
> Best, Steven

Hi @stevenweaver I kept on troubleshooting and found this difference between the files.
I checked the json files under https://www.jsonlint.com/ and found that at line 303859 on the "bad" json file there an issue. I do not know what could have cause this or how to fix it or if that is even the issue.

![bad json](https://user-images.githubusercontent.com/85318322/151225731-d33cdc37-1b0e-4d9c-91f7-45410db321d0.PNG)
![good json](https://user-images.githubusercontent.com/85318322/151225733-1423896e-c438-4186-bb19-8b6fe1d75938.PNG)

**Comment by stevenweaver** [comment]
Dear @RoberthAnthonyRojasChavez, 

Yes, `inf` violates JSON standard, covered in issues veg/hyphy#1320 and veg/hyphy#261. 

I've reopened veg/hyphy#261, but will keep this issue open as well to see if I can regex out `inf` before trying to parse the results page as JSON. 

Best,
Steven

**Comment by spond** [comment]
Infinity recorded for the log likelihood indicates an internal error. Could be an unhandled underflow for large multifurcating trees. Can you please share the file and the run settings? Privately by email if necessary.

**Comment by RoberthAnthonyRojasChavez** [comment]
To view Tree.txt, sign in<https://iowa-my.sharepoint.com/personal/rojaschavez_uiowa_edu/_layouts/15/acceptinvite.aspx?invitation=%7BF5FBEBA9%2DFB46%2D45FD%2D92CF%2DA9AEC435AB41%7D&listId=9cb798e9%2D18f0%2D42db%2Da1d7%2D55043e833d16&itemId=9f5cd08f%2D4f56%2D484f%2D8ec6%2D6e1880dbcb7e> or create an account.

**Comment by RoberthAnthonyRojasChavez** [comment]
To view Original Sequence Aligment.txt, sign in<https://iowa-my.sharepoint.com/personal/rojaschavez_uiowa_edu/_layouts/15/acceptinvite.aspx?invitation=%7B0AC7FE55%2D49A5%2D4113%2D941E%2D150AF80DE157%7D&listId=9cb798e9%2D18f0%2D42db%2Da1d7%2D55043e833d16&itemId=ab725b16%2D7284%2D47bc%2D8c49%2Dd03d93520c47> or create an account.

**Comment by RoberthAnthonyRojasChavez** [comment]
To view Json_output.txt, sign in<https://iowa-my.sharepoint.com/personal/rojaschavez_uiowa_edu/_layouts/15/acceptinvite.aspx?invitation=%7B99DB9E6D%2DFE6C%2D423B%2D9062%2DE8EC0A2605A7%7D&listId=9cb798e9%2D18f0%2D42db%2Da1d7%2D55043e833d16&itemId=de7ae0e6%2Dca74%2D454b%2Db927%2D2d5eb8c823f8> or create an account.

**Comment by RoberthAnthonyRojasChavez** [comment]
To view Sequence Aligment fragment.txt, sign in<https://iowa-my.sharepoint.com/personal/rojaschavez_uiowa_edu/_layouts/15/acceptinvite.aspx?invitation=%7B4E76AFBC%2D60DA%2D4671%2DA5A6%2DB5CB18BA4B3E%7D&listId=9cb798e9%2D18f0%2D42db%2Da1d7%2D55043e833d16&itemId=f798b5e6%2Ddaf2%2D4cf3%2D8df1%2D5ab59a87ca25> or create an account.
