### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by ayssel-uct** [veg/hyphy-vision#848]
I would like to visualize my HyPhy results (FUBAR and MEME json files), this page did not bring me any closer to understsanding how I can view those json files.  Your end-users are more likely to be biologists than they are to be programmers, hence it would bennefit your end users to have more detailed instructions, especially because not everyone is familiar with the json format.

**Comment by stevenweaver** [comment]
Dear @ayssel-uct, 

Sorry for your frustration. 

Have you tried http://vision.hyphy.org? I've attached a screenshot to show where you can click `Load` and select the JSON file you'd like to visualize. 

Further resources regarding general use of HyPhy are found [here](http://hyphy.org/resources/).

Best,
Steven

<img width="1728" alt="Screenshot 2022-11-16 at 6 32 13 AM" src="https://user-images.githubusercontent.com/535261/202181825-0c3a0dea-caa6-4c85-9e3f-ad1796f9f0c5.png">

**Comment by ayssel-uct** [comment]
Thanks a lot Steven, I did not expect such a quick answer. Much appreciated.
This helps a lot already.
I have>100 json files from FUBAR and was hoping that I could somehow automate the process of producing readable reports. Any suggestions would be welcome

**Comment by ayssel-uct** [comment]
This is probably on the wrong thread (I'll make that comment on the hyphy page), but a csv formatted table with the distribution values and probabilities  would have been more userfriendly than a .json file

**Comment by spond** [comment]
Dear @ayssel-uct,

FUBAR (and other standard analyses) print a summary in a "report-like" MarkDown format to standard out **in addition** to the detailed JSON file.

For example,

```
$hyphy fubar --alignment tests/data/bglobin.nex

...

### Computing the phylogenetic likelihood function on the grid 
* Determining appropriate tree scaling based on the best score from a  20 x 20 rate grid
* Best scaling achieved for 
	* synonymous rate =  2.815
	* non-synonymous rate =  0.714
* Computing conditional site likelihoods on a 20 x 20 rate grid

### Running an iterative zeroth order variational Bayes procedure to estimate the posterior mean of rate weights
* Using the following settings
	* Dirichlet alpha  : 0.5

### Tabulating site-level results
|     Codon      |   Partition    |     alpha      |      beta      |Posterior prob for positive selection|
|:--------------:|:--------------:|:--------------:|:--------------:|:-----------------------------------:|
|       11       |       1        |        0.549   |        2.208   |       Pos. posterior = 0.9514       |
|       21       |       1        |        0.295   |        0.918   |       Pos. posterior = 0.9119       |
|       42       |       1        |        0.572   |        2.328   |       Pos. posterior = 0.9503       |
|       48       |       1        |        0.749   |        2.659   |       Pos. posterior = 0.9341       |
|       50       |       1        |        0.917   |        4.917   |       Pos. posterior = 0.9473       |
|       54       |       1        |        0.798   |        2.905   |       Pos. posterior = 0.9259       |
|      123       |       1        |        1.268   |        5.640   |       Pos. posterior = 0.9092       |
----
## FUBAR inferred 7 sites subject to diversifying positive selection at posterior probability >= 0.9
Of these,  0.47 are expected to be false positives (95% confidence interval of 0-2 )

```

The `.json` file contains a much more complete report which allows to visualize/extract what they want with minimal restrictions. A `csv` file which is appropriate for dense tabular data, is not appropriate for storing diverse types of data (e.g. phylogenetic tree, ML estimates), in addition to table-like data.  

However, you can rather easily extract CSV from JSON using pretty much any modern scripting language (e.g Python), or a utility like [`jq`](https://stedolan.github.io/jq/):

```
$jq '(.["MLE"]["headers"] | map (. | .[0])) as $headers | $headers, .["MLE"]["content"]["0"][] | @csv' -r tests/data/bglobin.nex.FUBAR.json > bglobin_rates.csv
```

CSV files themselves are effectively intermediaries: people will rarely use them directly, rather they will read them into other tools and process them further. JSON serves the same purpose, it's just a better fit for the structured data that FUBAR and other analyses output.

Best,
Sergei

**Comment by ayssel-uct** [comment]
Dear Sergei, thank you for the thorough explanation and for pointing me to jq, this is really helpful.
