### ISSUE TITLE
ω distribution charts PNG export does not work

### ISSUE THREAD

**Issue by stevenweaver** [veg/hyphy-vision#85]
ω distribution charts PNG export does not work in Safari (nothing happens).

**Comment by stephenshank** [comment]
Which ω distribution chart are you referring to? Just now I was able to export PNGs for every chart in HyPhy Vision while using Safari.

**Comment by stevenweaver** [comment]
The issue appeared in relax results on datamonkey. However, I can no longer reproduce the error.
