### ISSUE TITLE
Cannot visualise FEL results in hyphy-vision

### ISSUE THREAD

**Issue by jaiganeshjg** [veg/hyphy-vision#868]
When I try to visualise the hyphy json output into hyphy-vision nothing happens. The data is not being loaded. Is it something to do with the data size? 

Attaching the json file - [fel.zip](https://github.com/veg/hyphy-vision/files/11756593/fel.zip)

**Comment by stephenshank** [comment]
Dear @jaiganeshjg,

Thank you for opening this issue. There appear to be `inf`s in some fields which was causing an error in the visualization code. I've replaced them with large floats (10^20), and the results now render.

I've placed a modified copy of your JSON here:
https://data.hyphy.org/web/issues/hyphy-vision_868.FEL.json

and your results may be viewed here:
http://vision.hyphy.org/FEL?resultsUrl=https://data.hyphy.org/web/issues/hyphy-vision_868.FEL.json

Let's keep this issue open until we decide what to do with those `inf`s. Please let me know if you have further questions.

Regards,
Stephen

**Comment by jaiganeshjg** [comment]
Thanks a lot.
