### ISSUE TITLE
Coloring for rows with significant p-values are not contrasting enough

### ISSUE THREAD

**Issue by stevenweaver** [veg/hyphy-vision#87]
The coloring are different shades of gray. They are so close in color that it is not immediately clear whether it is by design or a bug. 

<img width="980" alt="screen shot 2017-11-26 at 11 22 38 am" src="https://user-images.githubusercontent.com/535261/33242022-291d0de0-d29c-11e7-8379-43db1e4a20c8.png">

**Comment by stephenshank** [comment]
I used the same styles we currently use for highlighting sites under selection in FEL, MEME, etc, and invert it upon hover... see below.

![absrel-row](https://user-images.githubusercontent.com/8673708/34172321-a12ced84-e4bf-11e7-906c-976f50b4d9f1.gif)
