### ISSUE TITLE
Problems installing hyphy-vision

### ISSUE THREAD

**Issue by pirale** [veg/hyphy-vision#871]
Hello!

I am trying to install / run hyphy-vision, but cannot do so. I followed the instructions on the github landing page. I'm appending the output of running yarn to the end of this message.

Could you please help?

Thank you!

➤ YN0000: ┌ Resolution step
➤ YN0014: │ @hyphy_software/busted@https://api.observablehq.com/@hyphy_software/busted@3486.tgz?[...]: Only some patterns can be imported from legacy lockfiles (not "https://api.observablehq.com/@hyphy_software/busted@3486.tgz?v=3#1f904394320baad5f976e5434be7be88ccf95a3d")
➤ YN0014: │ @hyphy_software/fel-analysis-result-visualization@https://api.observablehq.com/@hyphy_software/fel-analysis-result-visualization@2311.tgz?[...]: Only some patterns can be imported from legacy lockfiles (not "https://api.observablehq.com/@hyphy_software/fel-analysis-result-visualization@2311.tgz?v=3#04c56ee58e9275a64c9cbd1b8df924dd89cab1d8")
➤ YN0014: │ @hyphy_software/gard-analysis-result-visualization@https://api.observablehq.com/@hyphy_software/gard-analysis-result-visualization@916.tgz?[...]: Only some patterns can be imported from legacy lockfiles (not "https://api.observablehq.com/@hyphy_software/gard-analysis-result-visualization@916.tgz?v=3#3460a7950dd35fc3d8e2c69a8721cf554dbd4b12")
➤ YN0014: │ @hyphy_software/multi-hit-analysis-result-visualization@https://api.observablehq.com/@hyphy_software/multi-hit-analysis-result-visualization.tgz?[...]: Only some patterns can be imported from legacy lockfiles (not "https://api.observablehq.com/@hyphy_software/multi-hit-analysis-result-visualization.tgz?v=3#2ebd1d1ab0d3bb24cbb94fcfa6f41d8b0be4c108")
➤ YN0014: │ @hyphy_software/nrm@https://api.observablehq.com/@hyphy_software/nrm@1578.tgz?[...]: Only some patterns can be imported from legacy lockfiles (not "https://api.observablehq.com/@hyphy_software/nrm@1578.tgz?v=3#5d2cb59f7771ec1ede48f62d9e25e41f526bdd4f")
➤ YN0013: │ @hyphy_software/busted@https://api.observablehq.com/@hyphy_software/busted@3486.tgz?[...] can't be found in the cache and will be fetched from the remote server
➤ YN0013: │ @hyphy_software/fel-analysis-result-visualization@https://api.observablehq.com/@hyphy_software/fel-analysis-result-visualization@2311.tgz?[...] can't be found in
➤ YN0013: │ @hyphy_software/gard-analysis-result-visualization@https://api.observablehq.com/@hyphy_software/gard-analysis-result-visualization@916.tgz?[...] can't be found i
➤ YN0013: │ @hyphy_software/multi-hit-analysis-result-visualization@https://api.observablehq.com/@hyphy_software/multi-hit-analysis-result-visualization.tgz?[...] can't be f
➤ YN0013: │ @hyphy_software/nrm@https://api.observablehq.com/@hyphy_software/nrm@1578.tgz?[...] can't be found in the cache and will be fetched from the remote server
➤ YN0061: │ eslint-loader@npm:4.0.2 is deprecated: This loader has been deprecated. Please use eslint-webpack-plugin
➤ YN0061: │ @fortawesome/fontawesome-svg-core@npm:1.3.0 is deprecated: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
➤ YN0061: │ popper.js@npm:1.16.1 is deprecated: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
➤ YN0032: │ nan@npm:2.14.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
➤ YN0061: │ @babel/preset-es2015@npm:7.0.0-beta.53 is deprecated: 👋 We've deprecated any official yearly presets in 6.x in favor or babel-preset-env. For 7.x it would be @babel/preset-env.
➤ YN0061: │ @babel/plugin-proposal-class-properties@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
➤ YN0001: │ Error: @hyphy_software/busted@https://api.observablehq.com/@hyphy_software/busted@3486.tgz?[...]: Manifest not found
    at zA.find (/Users/pirona01/.yarn/releases/yarn-3.6.3.cjs:390:32033)
    at async /Users/pirona01/.yarn/releases/yarn-3.6.3.cjs:601:11488
    at async Object.a0e (/Users/pirona01/.yarn/releases/yarn-3.6.3.cjs:390:11001)
    at async Jb.resolve (/Users/pirona01/.yarn/releases/yarn-3.6.3.cjs:601:11449)
    at async kf.resolve (/Users/pirona01/.yarn/releases/yarn-3.6.3.cjs:391:1400)
    at async kf.resolve (/Users/pirona01/.yarn/releases/yarn-3.6.3.cjs:391:1400)
    at async /Users/pirona01/.yarn/releases/yarn-3.6.3.cjs:439:6681
    at async df (/Users/pirona01/.yarn/releases/yarn-3.6.3.cjs:390:11064)
    at async _ (/Users/pirona01/.yarn/releases/yarn-3.6.3.cjs:439:6663)
    at async Promise.allSettled (index 16)
➤ YN0000: └ Completed in 2s 744ms
➤ YN0000: Failed with errors in 2s 746ms
➤ YN0061: core-js@npm:2.6.12 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: @babel/plugin-proposal-numeric-separator@npm:7.16.7 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
➤ YN0061: @babel/plugin-proposal-object-rest-spread@npm:7.18.0 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
➤ YN0061: @babel/plugin-proposal-optional-chaining@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
➤ YN0061: @babel/plugin-proposal-optional-catch-binding@npm:7.16.7 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
➤ YN0061: @babel/plugin-proposal-private-property-in-object@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-property-in-object instead.
➤ YN0061: clipboard-js@npm:0.3.6 is deprecated: Please migrate to https://github.com/lgarron/clipboard-polyfill
➤ YN0061: @fortawesome/fontawesome-common-types@npm:0.3.0 is deprecated: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
➤ YN0061: @babel/plugin-proposal-async-generator-functions@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
➤ YN0061: @babel/plugin-proposal-logical-assignment-operators@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
➤ YN0061: rollup-plugin-node-resolve@npm:3.4.0 is deprecated: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
➤ YN0061: @babel/plugin-proposal-export-namespace-from@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
➤ YN0061: @babel/plugin-proposal-class-static-block@npm:7.18.0 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-static-block instead.
➤ YN0061: @babel/plugin-proposal-json-strings@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
➤ YN0061: @babel/plugin-proposal-nullish-coalescing-operator@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
➤ YN0061: @babel/plugin-proposal-dynamic-import@npm:7.16.7 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
➤ YN0061: @babel/plugin-proposal-private-methods@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
➤ YN0061: @babel/plugin-proposal-unicode-property-regex@npm:7.17.12 is deprecated: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
➤ YN0061: har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0061: uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0032: fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: fsevents@npm:1.2.13 is deprecated: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
➤ YN0032: nan@npm:2.16.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: mini-create-react-context@npm:0.3.3 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: querystring@npm:0.2.0 is deprecated: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
➤ YN0061: browserslist@npm:1.7.7 is deprecated: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
➤ YN0061: circular-json@npm:0.3.3 is deprecated: CircularJSON is in maintenance only, flatted is its successor.
➤ YN0061: flatten@npm:1.0.3 is deprecated: flatten is deprecated in favor of utility frameworks such as lodash.
➤ YN0061: svgo@npm:0.7.2 is deprecated: This SVGO version is no longer supported. Upgrade to v2.x.x.
➤ YN0061: source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: @npmcli/move-file@npm:1.1.2 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: core-js-pure@npm:3.15.1 is deprecated: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.
➤ YN0061: urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0061: resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated

**Comment by stevenweaver** [comment]
Dear @pirale, 

Could you do me a solid and let me know which version of node you are using?

Additionally, would it be possible to start with a clean directory (no pre-existing `node_modules` directory)?

Best,
Steven
