### ISSUE TITLE
Installation issues: CMake Error from source, PackagesNotFoundError from conda

### ISSUE THREAD

**Issue by singing-scientist** [veg/hyphy-vision#889]
Greetings, and thanks so much for HyPhy! I'm having trouble installing from source (and from conda).

**System info:** Apple M2 Max, MacOS Sonoma Version 14.5

**FROM SOURCE.** When attempting, I downloaded hyphy-2.5.62.tar.gz, decompressed, and tried the following at the Terminal:

```
cd hyphy-2.5.62
cmake .
make MP
make install
```

Upon running the `make install`, I receive the following error:

```
[100%] Built target hyphy
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/share/hyphy
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot make directory "/usr/local/share/hyphy": No such file
  or directory.


make: *** [install] Error 1
```

I also tried running with `cmake -DCMAKE_INSTALL_PREFIX=/usr/local/bin`, a directory that already exists, to no avail. I also tried running the suggestions in [this issue](https://github.com/veg/hyphy/issues/1636), which did not fix the error:

```
brew install gcc
rm -rf CMakeFiles CMakeCache*
CC=/usr/bin/gcc CXX=/usr/bin/g++ cmake ./
make
```

**USING CONDA.** When attempting, I receive a simple error that says it doesn't exist.

```
conda install -c bioconda hyphy
Channels:
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - hyphy

Current channels:

  - https://conda.anaconda.org/bioconda
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Apologies if I missed something obvious; very grateful for any direction you could provide!

**Comment by spond** [comment]
Dear @singing-scientist,

It looks like when you build the package the binaries are made in the `hyphy-2.5.62` directory (check to confirm), but when you type `make install`, an attempt is made to write the binaries and libraries to the standard `/usr/local/bin` and `/usr/local/share` installation targets. On `MacOS X`, these are not writeable by a common user. You can do one of two things

1. Just run HyPhy from the build directory (`./hyphy`)
2. Try `sudo make install`

Best,
Sergei

**Comment by singing-scientist** [comment]
Thank you so much, @spond — 'sudo' did the trick! Really appreciate your help with this.

Best,
Chase
