### ISSUE TITLE
Create JSON explorer with link to data dictionaries for each page

### ISSUE THREAD

**Issue by stevenweaver** [veg/hyphy-vision#95]
We should provide a simple JSON value explorer that researchers can click on to review. We should also have links to data dictionaries for each analysis on the same page. Options to export in different data formats like CSV might also be useful.

**Comment by stephenshank** [comment]
There is an [open source React component for viewing JSON](https://github.com/mac-s-g/react-json-view) that was pretty easy to get going:

![json-viewer](https://user-images.githubusercontent.com/8673708/33907863-98718ec2-df54-11e7-854a-da87a735703c.gif)

**Comment by stevenweaver** [comment]
Perfect. Theoretically, our pages should be informative enough for researchers not to need it, but there was enough interest to give them an option to take a look at it in an easy way. I'm thinking we might squirrel it away under the Export dropdown or at the bottom of the page since it's more of an advanced option.

We can link to @sjspielman's JSON documentation as well. That should be ample support for folks who want to customize reporting for their publications from our end.
